services:
  dashboard:
    build: .
    container_name: alfredo_dashboard
    command: streamlit run ui/dashboard.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true --server.maxUploadSize=2000
    ports:
      - "8501:8501"
      - "8000:8000"
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - PYTHONPATH=/app
    volumes:
      - ./db:/app/db
      - ./workspace:/app/workspace
      - ./storage:/app/storage
    restart: unless-stopped


