import os
import json
from core.db_manager import DBManager

def seed_startapp_example():
    if os.path.exists(".seed_completed"):
        print("Example workflow already seeded. Skipping to preserve user modifications.")
        return

    db = DBManager()
    
    print("Creating models...")
    # Models
    try:
        model_4_id = db.create_model("google", "gemini-2.5-flash", "GEMINI_API_KEY", False, 0.0)
    except Exception:
        db.cursor.execute("SELECT id FROM models WHERE model_name = 'gemini-2.5-flash'")
        res = db.cursor.fetchone()
        model_4_id = res['id'] if res else None

    try:
        model_6_id = db.create_model("google", "gemini-3.5-flash", "GEMINI_API_KEY", False, 0.0)
    except Exception:
        db.cursor.execute("SELECT id FROM models WHERE model_name = 'gemini-3.5-flash'")
        res = db.cursor.fetchone()
        model_6_id = res['id'] if res else None

    print("Creating agents...")
    try:
        socrate_id = db.create_agent(
            name="Socrate",
            role="{specialization} Dialectical Thinker  Ideation Architect",
            backstory="Goal: Evaluate, stress-test, or expand concepts and proposals using a strictly {specialization} cognitive framework.\n\nBackstory: You are an intellectual powerhouse inspired by Socratic dialectics, executing your analysis through a highly focused analytical lens. Your current mindset, persona, and cognitive framework are strictly defined as {specialization}. You must view every idea, proposal, or process through this specific filter, adhering strictly to its rules. If your current {specialization} approach is critical or pessimistic, you must relentlessly hunt for logical flaws, hidden risks, and systemic bottlenecks. If your approach is optimistic or constructive, you must uncover latent value, optimistic upside potentials, and strategic strengths. If your approach is creative or expansive, you must generate lateral extensions and push boundaries. You never break character you enforce the specific cognitive rules of being {specialization} to help the user thoroughly analyze their ideas.",
            model_id=model_4_id,
            tools=[]
        )
    except Exception:
        db.cursor.execute("SELECT id FROM agents WHERE name = 'Socrate'")
        res = db.cursor.fetchone()
        socrate_id = res['id'] if res else None

    try:
        patrick_id = db.create_agent(
            name="Patrick",
            role="Pragmatic Business Development Strategist specialized in {specialization}",
            backstory="Goal: Transform abstract concepts into commercially viable, execution-ready models by providing concrete, actionable steps filtered through the strict lens of {specialization}.\n\nBackstory: You are a battle-tested entrepreneur and corporate strategist known for your ruthless pragmatism. You do not deal in fluffy concepts, vague promises, or idealistic scenarios your sole purpose is to bridge the gap between imagination and execution. You evaluate proposals with a highly critical, realistic mindset, specifically analyzing their viability through the restrictive filter of {specialization}.\n\nIf your current focus is economic, you ruthlessly dissect unit economics, resource allocation, and revenue streams. If it is technological, you audit implementation complexity, technical debt, and scalability. If it is time-oriented, you map out cutthroat roadmaps, milestones, and critical paths. You always filter out the noise and deliver a clear, pragmatic, step-by-step implementation roadmap outlining exactly how to operationalize the idea under the strict constraints of {specialization}.",
            model_id=model_4_id,
            tools=[]
        )
    except Exception:
        db.cursor.execute("SELECT id FROM agents WHERE name = 'Patrick'")
        res = db.cursor.fetchone()
        patrick_id = res['id'] if res else None

    print("Creating tasks...")
    
    def get_or_create_task(desc, **kwargs):
        db.cursor.execute("SELECT id FROM tasks WHERE description = ?", (desc,))
        res = db.cursor.fetchone()
        if res:
            return res['id']
        return db.create_task(description=desc, **kwargs)

    # Task 1
    task1_id = get_or_create_task(
        desc="Analyze the following user idea: {idea}. Focus exclusively on positive\naspects, future scalability, and competitive advantages. What is the best-case scenario? How\ncould it revolutionize the users workflow?",
        expected_output="A bulleted list of at least 5 main strengths and 3 long-term opportunities\ngenerated by the idea.",
        agent_id=socrate_id,
        agent_specialization="Positive thinker",
        tools=[],
        required_inputs=[{"key": "idea", "prompt": "What is the idea?"}],
        model_id=model_4_id,
        name=None
    )

    # Task 8
    task8_id = get_or_create_task(
        desc="Analyze the idea: {idea}. Identify critical risks, execution difficulties, and potential problems.",
        expected_output="Generate an output with two keys: short_term_problems and long_term_problems. short_term_problems must be an array of at least 5 strings describing immediate weaknesses. long_term_problems must be an array of at least 3 strings describing probable long-term issues.",
        agent_id=socrate_id,
        agent_specialization="Critical thinker",
        tools=[],
        required_inputs=[],
        model_id=None,
        name=None
    )

    # Task 9
    task9_id = get_or_create_task(
        desc="1. Analyze previous tasks results using the 'read_atomic_memory' tool to fetch data from the Ephemeral Workspace Memory Index.\n2. Generate a practical and feasible action plan.\n3. Identify required modifications to ensure viability.\n4. List the first 5 practical implementation steps.",
        expected_output="A JSON object with two keys:\n- action_plan: A string detailing the comprehensive, viable plan, including all required optimizations and modifications.\n- initial_steps: An array of 5 strings, each describing a concrete first step to begin implementation.",
        agent_id=patrick_id,
        agent_specialization="innovative business manager",
        tools=["search_web", "read_atomic_memory"],
        required_inputs=[],
        model_id=model_6_id,
        name="Starting plan development"
    )

    print("Creating workflow...")
    # Constructing DAG task_ids
    task_ids_json = [
        {"id": "node_0_a14fb9", "task_id": task1_id, "depends_on": [], "execution_level": 1},
        {"id": "node_1_ee8a50", "task_id": task8_id, "depends_on": [], "execution_level": 1},
        {"id": "node_2_561280", "task_id": task9_id, "depends_on": ["node_0_a14fb9", "node_1_ee8a50"], "execution_level": 2}
    ]

    try:
        db.create_workflow(
            name="Startapp evaluation",
            task_ids=task_ids_json,
            requires_human_check=True,
            expected_exports=["text"],
            export_instructions=""
        )
    except Exception:
        pass # Workflow might already exist

    # Mark as completed
    with open(".seed_completed", "w") as f:
        f.write("completed")

    print("Seeding complete! You can now view the 'Startapp evaluation' workflow in your UI.")

if __name__ == "__main__":
    seed_startapp_example()
