import os
import json
from core.db_manager import DBManager

def seed_startup_example():
    if os.path.exists(".seed_completed"):
        print("Example workflow already seeded. Skipping to preserve user modifications.")
        return

    db = DBManager()
    
    print("Creating model...")
    # Add a generic model
    try:
        model_id = db.create_model("openai", "gpt-4o", "OPENAI_API_KEY", False, 0.0)
    except Exception:
        # If the model already exists (e.g. from a partial previous run), fetch its ID
        db.cursor.execute("SELECT id FROM models WHERE model_name = 'gpt-4o'")
        model_id = db.cursor.fetchone()['id']

    print("Creating generic agents...")
    try:
        researcher_id = db.create_agent(
            name="The Generic Researcher",
            role="{specialization} Researcher & Data Gatherer",
            backstory="You are a relentless investigator dedicated to {specialization}. You excel at navigating complex directories and scraping the web to compile highly accurate reports. You do not modify anything; your sole purpose is to gather data and summarize it accurately.",
            model_id=model_id,
            tools=["search_web", "read_file"]
        )
    except Exception:
        db.cursor.execute("SELECT id FROM agents WHERE name = 'The Generic Researcher'")
        researcher_id = db.cursor.fetchone()['id']

    try:
        analyst_id = db.create_agent(
            name="The Generic Analyst",
            role="{specialization} Analyst & Strategist",
            backstory="You are a brilliant thinker specialized in {specialization}. You evaluate raw inputs to identify flaws, uncover hidden potential, or ground ideas in reality.",
            model_id=model_id,
            tools=[]
        )
    except Exception:
        db.cursor.execute("SELECT id FROM agents WHERE name = 'The Generic Analyst'")
        analyst_id = db.cursor.fetchone()['id']
    
    try:
        master_ai_id = db.create_agent(
            name="Master AI",
            role="Chief Orchestrator & System Modifier",
            backstory="You are the central brain and project manager. You review the specialized agents' work. You are the ONLY agent authorized to use write tools or terminal commands.",
            model_id=model_id,
            tools=["write_file", "terminal_executor"]
        )
    except Exception:
        db.cursor.execute("SELECT id FROM agents WHERE name = 'Master AI'")
        master_ai_id = db.cursor.fetchone()['id']

    print("Creating tasks with specializations...")
    task1_id = db.create_task(
        description="Analyze the following user startup idea: {user_input}. Focus exclusively on positive aspects, future scalability, and competitive advantages.",
        expected_output="A bulleted list of at least 5 main strengths and 3 long-term opportunities generated by the idea.",
        agent_id=analyst_id,
        agent_specialization="Startup Visionary",
        tools=[],
        name="Analysis of Potential"
    )

    task2_id = db.create_task(
        description="Critically evaluate the following user startup idea: {user_input}. Find every reason it might fail. Consider technical limitations, ethical concerns, cost/benefit ratios, and potential maintenance headaches.",
        expected_output="A detailed 'Red Flag' report identifying at least 5 critical risks and 3 reasons why the user should proceed with caution or change direction.",
        agent_id=analyst_id,
        agent_specialization="Startup Risk",
        tools=[],
        name="Stress Test & Risk Assessment"
    )

    task3_id = db.create_task(
        description="Evaluate the execution requirements for: {user_input}. What tools are needed? How long will it take to build an MVP?",
        expected_output="A technical feasibility score (1-10) and a step-by-step 30-day implementation roadmap.",
        agent_id=analyst_id,
        agent_specialization="Startup Pragmatic Realist",
        tools=[],
        name="Practical Feasibility Check"
    )
    
    task4_id = db.create_task(
        description="Review the reports generated by the previous tasks. Balance their views and provide a final executive summary to the user. Should we proceed, modify, or discard the startup idea? Write the final report using your tools.",
        expected_output="A final 'Go/No-Go' recommendation with a summary balancing optimism, caution, and operational reality.",
        agent_id=master_ai_id,
        agent_specialization="Startup Executive",
        tools=["write_file"],
        name="Final Synthesis"
    )

    print("Creating workflow...")
    try:
        db.create_workflow(
            name="Startup Ideas Brainstorming",
            task_ids=[task1_id, task2_id, task3_id, task4_id],
            requires_human_check=True,
            expected_exports=["markdown"],
            export_instructions="Format the final business plan beautifully in markdown."
        )
    except Exception:
        pass # Workflow might already exist if the user is rerunning without a clean state

    # Mark as completed
    with open(".seed_completed", "w") as f:
        f.write("completed")

    print("Seeding complete! You can now view the 'Startup Ideas Brainstorming' workflow in your UI.")

if __name__ == "__main__":
    seed_startup_example()
