"""
tools/custom_tools.py

This file contains custom tools generated by the AI Tool Factory.
Tools in this file are automatically loaded by the Crew Builder.
"""

from crewai.tools import tool
import os
import requests
import json
import logging

logger = logging.getLogger(__name__)

# --- CUSTOM TOOLS BELOW THIS LINE ---
